# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

plugins: [jekyll-paginate,jekyll-gist]

# Setup
title:            Coding fw
tagline:          '一个安静地方'
description:      'A brazen two-column <a href="http://www.fwcode.top" target="_blank">fwcode</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://github.com/Wsxiaojian" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Fanwei'
  url:            www.fwcode.top

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Wsxiaojian
